# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NjRkZjRmNWQxYTc5OWY4MjI4ZjIyYTUzODdlZGYxYmYxNGQxZDM0ZDQzMTBmYTVlODEzZWRkY2EzZGIzOGQxOGRjYjUzZDUyM2YyNGViYzc2MWEwYWJmNDdkZTI0Njc1Y2ZjOTMyZjc3YTZkYzY4ZjFmNzA4M2IyZWMxYzJlYzU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
